# Generated by Django 6.0.3 on 2026-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='pin',
            field=models.CharField(blank=True, help_text='4-6 digit PIN for kiosk authentication', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Unique staff ID for kiosk check-in', max_length=20, null=True, unique=True),
        ),
    ]
