# Generated by Django 6.0.3 on 2026-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_staff_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='show_on_frontend',
            field=models.BooleanField(default=False, help_text='Show this staff member on the public team page'),
        ),
    ]
