# Generated by Django 6.0.3 on 2026-04-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_show_on_frontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('assigned_by', models.CharField(max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.teammember')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shifttype')),
            ],
            options={
                'ordering': ['-assignment_date', 'shift_type__start_time'],
                'unique_together': {('staff', 'assignment_date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('absent', 'Absent'), ('incomplete', 'Incomplete'), ('excessive_duration', 'Excessive Duration')], default='absent', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shifttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.teammember')),
            ],
            options={
                'ordering': ['-attendance_date', 'assigned_shift_type__start_time'],
                'unique_together': {('staff', 'attendance_date', 'assigned_shift_type')},
            },
        ),
    ]
