# Generated by Django 6.0.3 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_staff_attendance_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='pin',
            field=models.CharField(blank=True, help_text='4-6 digit PIN for kiosk authentication', max_length=6, null=True, unique=True),
        ),
    ]
